import assert from 'node:assert/strict';
import { generatedStart, isGeneratedWorld, GENERATED_ATTRIBUTION } from '../src/compiler/generated-start.ts';
import { locationFromSearch, inUSBox, supportedCountryCode, PICKER_COUNTRY_CODES } from '../src/ui/spawn-query.ts';
import { continuationDistrict } from '../src/compiler/continuation.ts';
import { terrainSampler } from '../src/compiler/terrain.ts';
const loc = { lat: 38.79, lon: -98.52, name: 'Kansas test pin' };
const start = performance.now(), world = generatedStart(loc);
assert.deepEqual(world, generatedStart(loc));
assert.deepEqual(world.bounds, { minX: -400, minZ: -400, maxX: 400, maxZ: 400 });
assert(isGeneratedWorld(world)); assert(world.name.includes('generated world')); assert.deepEqual(world.attribution, [GENERATED_ATTRIBUTION]);
assert(world.roads.length >= 6 && world.buildings.length >= 6 && world.cameras.length >= 4 && world.trees.length > 0);
assert(world.terrain.heights.every(Number.isFinite));
assert(world.cameras.some(c => Math.hypot(c.p[0] - world.spawn.p[0], c.p[1] - world.spawn.p[1]) < 25));
const connected = new Set<number>([world.graph.edges[0].from]);
for (let i = 0; i < world.graph.nodes.length; i++) for (const e of world.graph.edges) if (connected.has(e.from)) connected.add(e.to);
assert.equal(connected.size, world.graph.nodes.length, 'All roads and intersections form one connected drivable network');
const h = terrainSampler(world.terrain);
const next = continuationDistrict(world, { minX: 400, minZ: -400, maxX: 800, maxZ: 400 }, [{ recipe: world, heightAt: h, groundAt: h }]);
assert(next.roads.some(r => r.pts.some(p => p[0] >= 800))); assert(next.graph.edges.length > 0); assert(isGeneratedWorld(next));
assert.throws(() => generatedStart({ ...loc, lat: NaN }));
const cities = [{ id: 'boulder', name: 'Boulder', lat: 40, lon: -105 }];
assert.equal(locationFromSearch('?autostart', cities)?.baked, 'boulder');
assert.equal(locationFromSearch('?autostart&lat=38.79&lon=-98.52&mode=freeroam', cities)?.baked, undefined);
assert.equal(locationFromSearch('?autostart&lat=38.79&lon=-98.52&mode=freeroam', cities)?.mode, 'freeroam');
for (const q of ['?autostart&lat=NaN&lon=0', '?autostart&lat=&lon=0', '?autostart&lat=91&lon=0', '?autostart&lat=0&lon=181', '?autostart&lat=10', '?autostart&city=unknown', '?lat=10&lon=20']) assert.equal(locationFromSearch(q, cities), null, q);
for (const [lat, lon] of [[18.3419, -64.9307], [17.747, -64.703], [18.466, -66.106], [40.0176, -105.2797]]) assert(inUSBox(lat, lon), `Supported US or territory pin ${lat}, ${lon}`);
for (const code of ['us', 'pr', 'vi', 'VI', undefined]) assert(supportedCountryCode(code));
for (const code of ['vg', 'ca', 'mx']) assert(!supportedCountryCode(code));
assert(!inUSBox(0, 0)); assert(!inUSBox(NaN, -64.93));
assert.deepEqual(PICKER_COUNTRY_CODES.split(','), ['us', 'pr', 'vi']);
console.log(`Generated startup regressions passed: deterministic geometry, connected roads, nearby objectives, continuation and validated URL pins (${Math.round(performance.now() - start)} ms)`);
